version: '3.3'

services:

  tasks:
    container_name: tasks
    build:
      context: ./services/tasks
      dockerfile: Dockerfile-prod
    expose:
      - '5000'
    environment:
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@tasks-db:5432/tasks_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@tasks-db:5432/tasks_test
    depends_on:
      - tasks-db
    links:
      - tasks-db

  tasks-db:
    container_name: tasks-db
    build:
      context: ./services/tasks/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    container_name: nginx
    build: ./services/nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      - tasks
    links:
      - tasks
